runtime: python37

handlers:
- url: /static
  static_dir: static

- url: /static/fish_pics
  static_dir: static/fish_pics

- url: /static/post_pics
  static_dir: static/post_pics

- url: /static/profile_pics
  static_dir: static/profile_pics

- url: /.*
  script: auto

runtime_config:
    python_version: 3
