from fishbook.models import User, Post, Comment, Fish, Notice, AlchemyEncoder
from fishbook import db, bcrypt
db.drop_all()
db.create_all()
password='123456'
hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')
user1 = User(username='wangyi1', email='wangyi1@mail.com', password=hashed_password,admin=True,follow=[2,3,4],black=[5])
user2 = User(username='wangyi2', email='wangyi2@mail.com', password=hashed_password,follow=[1])
user3 = User(username='wangyi3', email='wangyi3@mail.com', password=hashed_password,follow=[1])
user4 = User(username='wangyi4', email='wangyi4@mail.com', password=hashed_password,follow=[1])
user5 = User(username='wangyi5', email='wangyi5@mail.com', password=hashed_password)
db.session.add(user1)
db.session.add(user2)
db.session.add(user3)
db.session.add(user4)
db.session.add(user5)
db.session.commit()

post1_1=Post(content='post1 from user1', user_id = 1)
post2_1=Post(content='post1 from user2', user_id = 2)
post3_1=Post(content='post1 from user3', user_id = 3)
post4_1=Post(content='post1 from user4', user_id = 4)
post5_1=Post(content='post1 from user5', user_id = 5)
db.session.add(post1_1)
db.session.add(post2_1)
db.session.add(post3_1)
db.session.add(post4_1)
db.session.add(post5_1)

post1_2=Post(content='post2 from user1', user_id = 1)
post2_2=Post(content='post2 from user2', user_id = 2)
post3_2=Post(content='post2 from user3', user_id = 3)
post4_2=Post(content='post2 from user4', user_id = 4)
post5_2=Post(content='post2 from user5', user_id = 5)

db.session.add(post1_2)
db.session.add(post2_2)
db.session.add(post3_2)
db.session.add(post4_2)
db.session.add(post5_2)
db.session.commit()

fish0=Fish(id=0,name='Black bream',image_file='Black bream.jpg')
fish1=Fish(id=1,name='Black grouper',image_file='Black grouper.jpg')
fish2=Fish(id=2,name='Bluefin tuna',image_file='Bluefin tuna.jpg')
fish3=Fish(id=3,name='Mahi-mahi',image_file='Mahi-mahi.jpg')
fish4=Fish(id=4,name='Sailfish',image_file='Sailfish.jpg')
fish5=Fish(id=5,name='Yellowtail',image_file='Yellowtail.jpg')

db.session.add(fish0)
db.session.add(fish1)
db.session.add(fish2)
db.session.add(fish3)
db.session.add(fish4)
db.session.add(fish5)

db.session.commit()
